### ISSUE TITLE
Add a global parameter to all routes

### ISSUE THREAD

**Issue by Fredyy90** [studio107/Mindy_Router#2]
Hi,

I would like to add a global parameter to all routes e.g the current locale is there a way to config this without changing all routes manualy?

Greetings,
Frederick

**Comment by max107** [comment]
Hi @Fredyy90. 

It's possible via override `UrlManager`. 

***pass parameter as url segment***

Example:
```php
<?php

namespace Mindy\Router;

class LangUrlManager extends UrlManager
{
    public $lang = 'en';

    public function reverse($name, $args = [])
    {
        if (strpos($name, 'admin') === false) {
            $args = array_merge(['lang' => $this->lang], $args);
        }
        return parent::reverse($name, $args);
    }
}
```

global urls.php looks like:
```php
// "?" - is a optional parameter
'/{lang:c}?/page/' => new Patterns('Modules.Pages.urls', 'page'),
```

Result url: `/en/page/example`

***pass parameter in query***

```php
<?php

namespace Mindy\Router;

class LangUrlManager extends UrlManager
{
    public $lang = 'en';

    public function reverse($name, $args = [])
    {
        $url = parent::reverse($name, $args);
        if (strpos($url, '?') === false) {
            $url .= '?lang=' . $this->lang;
        } else {
            $url .= '&lang=' . $this->lang;
        }
        return $url;
    }
}
```

Result url: `/page/example?lang=en`

Solution 2 is better, because you can transparent turn on / off language manager without change code in your project. If you using http://github.com/Studio107/Mindy_Orm you can override manager in your models and transparent pass parameter to query set.

```
class LangManager extends Manager
{
    public function getQuerySet()
    {
        $lang = '?'; // Project logic. Lang saved in session as example.
        return parent::getQuerySet()->filter(['lang' => $lang]);
    }
}
```

**Comment by max107** [comment]
Added abstract `BaseLangUrlManager` https://github.com/studio107/Mindy_Router/commit/c841c94525a0cd3b3c76c5ccc673250247e6df87

Sorry for my bad english :)

Thanks for using project.

**Comment by max107** [comment]
Closed
